travis:
  secure:
    BINSTAR_TOKEN: uuEHd7WkEL9FZf2TEAkIlFDgogOqiHAFJez3pFSa5Qw+t83CIEOBwdV22J4osnOpfLHYAs3sI+gIdmfXINN7c8NSQaUfyb1H1qkLKVgkcxpkOavvBgSZ4+9Uot+U6nkAD8SkirJ0XZHlm4tqTwWjyg/89fRBqlDVEZTvhDtT4bDrygBd709mI43CWgZy93X5T37FgRoUEDrQ1y6zRenhyiohwx01CVJj+o+z5PSdx7Kv2P8ugxyDrA85fTGjiUEETq3y14Y2aoNvmx81nZeimXfa8QVlnOlwvmzx6hV2NI7B5JQiG1ZKghd/nVGnufIuSHJcZCBacgPKvwM9N/h2KH7CnU8Qgbkt1+lr6oUw2HHHFuCINnzVHs4CE+0GKIVuiq9/7ShLXOqNclpFIXTi9MOv9P1Z3Y+gX1QO68EPxpyw3EphjZ2oV1rwgMGzmRhkgXLDwqEpomE6/2u1Jy7AbPojAV0EasgcJRPPdE30/i1mp2tUxe/+3Pt0QBa/o/nxGOsjrDkjSUCL669yUNz5Km0ckzdXRJkFdD4LNLqxwH/R/ZMk6vgaXlRPb518xkTZNeiosYB7Z9M/HRH7Gy0OFQf0ZKF4MBkmt9SuZoOjxo6OhS47fwvbZNwddB6OAJTRwrOHCNlZf8m7O1P6pHVHqHvt41QFzz8yRw8VHN/Owhk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
